version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hosted_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=api_main
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://api_user:secret@db:5432/api_main
      - PWD=secret
